INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Pablo", "pablito2244", 22, "Colorado 23", "Pablo2244", NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Luis", "luis0292", 29, "Tamaulipas 22", "Luis0292", NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Pedro", "pedro1243", 30, "Felipe 09", "Pedro1243", NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Cesar", "cesar93954", 21, "Chapultepec 44", "Cesar93954",  NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Gollo", "gollo42342", 50, "Luis Lopez 11", "Gollo42342", NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Romeo", "romeo34234", 33, "Enrique Diaz 98", "Romeo34234", NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Pipe", "pipe23542", 42, "Lago Azul 66", "Pipe23542", NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Polo", "polo432", 56, "Guillermo Diaz 71", "Polo432", NOW(), NOW());
INSERT INTO customers(name, username, age, address, password, created_at, updated_at) VALUES ("Nain", "nain111", 43, "Mariano Angeles 38", "Nain111", NOW(), NOW());

INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Disco duro STA3 1TB",86.99,5, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Memoria RAM DDR4 8GB",120,6, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Disco SSD 1 TB",150.99,4, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("GeForce GTX 1050tu",185,7, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("GeForce GTX 1080 Xtreme",755,6, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Monitor 24 LED Full HD",202,1, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Monitor 27 LED Full HD ", 245.99,1, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Portatil Yoga 520",559,2, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Portatil Ideapd 320",444,2, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Impresora HP Deskjet 3720",59.99,3, NOW(), NOW());
INSERT INTO products(name,price,stock, created_at, updated_at) VALUES ("Impresora HP Laserjet Pro M26nw",180,3, NOW(), NOW());